name: Deploy to staging

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_STG_API_KEY}}
          heroku_app_name: "medusa-stg" #Must be unique in Heroku
          heroku_email: "medusastg@outlook.com"
